package testPackaz;

import java.util.Hashtable;
import java.util.List;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import model.people.Owner;
import model.places.Grave;
import model.places.Sector;
import remote.FacadeBeanRemote;

public class MainTest {
	
	public static void main(String[] args) {
		
		test();		
		
	}
	
	public static void test(){
		try {
			Context context;
			Object result = null;
			Hashtable jndiProperties = new Hashtable();
			jndiProperties.put(Context.URL_PKG_PREFIXES, "org.jboss.ejb.client.naming");
			context = new InitialContext(jndiProperties);
			
			result = context.lookup("ejb:EJBEar/EJBServer//TestBean!testPakaz.TestBeanRemote");
			
			FacadeBeanRemote remote = (FacadeBeanRemote) result;
			
			List<Sector> sectors = remote.getSectorTree();
			
			for (Sector curSector : sectors) {
				System.out.println(curSector.getSectorNumber()+":");
				for (Grave curGrave : curSector.getGraves()) {
					System.out.println(curGrave.getGraveNumber() + ", ");
				}
			}
					
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
